#!/usr/bin/env bash
# Fixes Nginx to listen on port 80
sudo service nginx start
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
