#!/usr/bin/env bash
# This script for Display the contents of the current directory in list format
#  Displays only the part of the name after the first dash

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
